CREATE DATABASE LOGIN_ELENCO;

USE LOGIN_ELENCO;

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    CPF_USUARIO VARCHAR(45),
    NOME_USUARIO VARCHAR(45),
    SENHA_USUARIO VARCHAR(45)
);

SELECT * FROM USUARIOS;

INSERT INTO USUARIOS (CPF_USUARIO, NOME_USUARIO, SENHA_USUARIO) 
	VALUES (12345678910, 'admin', 'admin');

CREATE TABLE ELENCO_ATUAL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    POSICAO VARCHAR(45) NOT NULL,
    NUMERO INT NOT NULL,
    SALARIO FLOAT NOT NULL,
    SITUACAO VARCHAR(45) NOT NULL,
    IDADE INT NOT NULL
);

SELECT * FROM ELENCO_ATUAL;

INSERT INTO ELENCO_ATUAL
    (NOME, IDADE, POSICAO, NUMERO, SITUACAO, SALARIO)
    VALUES ("EDERSON MORAES", 29, "GOLEIRO", 31, "APTO", 150000),
           ("KYLIE WALKER", 33, "DEFENSOR", 2, "APTO", 300000),
           ("RÚBEN DIAS", 26, "DEFENSOR", 3, "APTO", 250000),
           ("MANUEL AKANJI", 27, "DEFENSOR", 25, "APTO", 180000),
           ("JOHN STONES", 29, "DEFENSOR", 5, "APTO", 170000),
           ("RODRIGO HERNÁNDEZ", 26, "MEIO CAMPISTA", 16, "APTO", 200000),
           ("KEVIN DE BRUYNE", 31, "MEIO CAMPISTA", 17, "APTO", 500000),
           ("ILKAY GUNDOGAN", 32, "MEIO CAMPISTA", 8, "APTO", 250000),
           ("BERNARDO SILVA", 28, "ATACANTE", 20, "APTO", 300000),
           ("JACK GREALISH", 27, "ATACANTE", 10, "APTO", 350000),
           ("ERLING HAALAND", 22, "ATACANTE", 9, "APTO", 500000);

SELECT * FROM ELENCO_ATUAL;